### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by shirshak55** [kiwicom/orbit-components#997] opened 2019-04-13 12:32 UTC
It seems definitely typed has also not supported. Is there workaround?

**Comment by tomashapl** [comment] 2019-04-15 13:30
> It seems definitely typed has also not supported. Is there workaround?

We are supporting `flow` There is still discussion about typescript support, but i am not able to answer you now. Sorry

**Comment by vepor** [comment] 2019-04-17 11:17
Closing, duplicate of #324.

**Closed by vepor** 2019-04-17 11:17 UTC
