### ISSUE TITLE
<InputField> longer suffix overflows layout in Firefox

### ISSUE THREAD

**Issue by tibor-kulcar** [kiwicom/orbit-components#756] opened 2019-01-16 15:10 UTC
Firefox: When suffix option with longer text is provided, input itself doesn't shrink sufficiently for suffix to be "inside" component layout.

## Expected Behavior
Component's layout shouldn't be affected by longer suffix.

## Steps to Reproduce
<img width="570" alt="screen shot 2019-01-16 at 16 01 52" src="https://user-images.githubusercontent.com/3975660/51257871-e1806900-19a8-11e9-851d-c8c670da5b20.png">

## Context (Environment)
Firefox Quantum 64.0.2 (64-bit) running on MacOs High Sierra 10.13.6

**Comment by xtursky** [comment] 2019-02-25 13:31
The above issue #792 (released in 0.30.0) didn't fix the problem.
It's still present in Firefox (65.0.1) and orbit-components 0.31.0
See attached file. Same problem can be seen in InputField in StoryBook.

![2019-02-25_141932](https://user-images.githubusercontent.com/1123830/53340553-9479a600-3909-11e9-8983-cf70a4bfc270.png)

**Comment by wEprous** [comment] 2019-02-25 14:08
Sorry, now I see where the problem is - only specific flexbox bug for Firefox. Gonna fix it.

**Closed** 2019-02-26 13:42 UTC
